version: "3"

services:
    ubuntu:
        build:
            context: ubuntu
            args:
                - APP_USER=appuser
                - UBUNTU_VERSION=18.04
                # - USERNAME=appuser
        image: ubuntu1804/vscode_vnc
        container_name: ubuntu1804-vscode_vnc
        environment:
            - APP_USER=appuser
            - VNC_PASSWORD=${VNC_PASSWORD}
            # - VNC_PORT=${VNC_PORT}
            # - NOVNC_PORT=${NOVNC_PORT}
        ports:
            - "5901:5901"
            - "6901:6901"
            # - "${VNC_PORT}:${VNC_PORT}"
            # - "${NOVNC_PORT}:${NOVNC_PORT}"
